
export const searchStateToGA = state => ({
  eventCategory: 'search',
  eventAction: 'click',
  eventLabel: state.query,
  dimension1: state.index,
  dimension2: state.onlyAmazon,
  dimension3: state.node,
  dimension4: state.brand
})

export const colors = {
  Primary: '#FBEF7E',
  Complement: '#515360',
}

export const tagline = 'Amazon Search, But Better'
export const subtagline = 'Find what you\'re searching for faster.'

export const generatePageTitle = q => q ?
  `Best ${q} on Amazon | fivestar` :
  `fivestar | ${tagline}`

export const defaultTopPicks = [
  {
    key: 'top-picks',
    heading: 'Top Picks',
    items: [
      {"title":"HP Chromebook 14 Intel Celeron 4GB 16GB 14-inch Google Chromebook Laptop","brand":"HP","detailPageUrl":"https://www.amazon.com/HP-Chromebook-14-Celeron-14-inch/dp/B0172GUW4I?SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B0172GUW4I", "key": "B0172GUW4I","image":"https://images-na.ssl-images-amazon.com/images/I/51L5LC72T8L.jpg","details":["Processor: Intel Celeron 2955U with Intel HD Graphics (1.4 GHz, 2 MB cache,...","RAM: 4GB SDRAM DDR3L 1600MHz (onboard) | Storage: 16GB eMMC Flash Drive","Optical Drive: None | Operating System: Chrome OS","Graphics Card: Intel HD Graphics | Display: 14-inch HD WLED Brightview flat..."],"formattedPrice":"$254.95"},
      {"title":"Hynes Eagle 40L Flight Approved Carry on Backpack (Gray)","brand":"Hynes Eagle","detailPageUrl":"https://www.amazon.com/Hynes-Eagle-Flight-Approved-Backpack/dp/B01JID3BAA?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01JID3BAA", "key": "B01JID3BAA","image":"https://images-na.ssl-images-amazon.com/images/I/41Daw5GPmtL.jpg","details":["Water Repellent Polyester; Dimensions: 20.1 x 13.4 x 9.8 inches/51 x 34 x 2...","Multiple exterior compression buckle straps for adjusting the height based ...","A true hands-free carry on with suppressible shoulder straps, easily to con...","1 front zip pocket with multiple interior slip pockets, second compartment ..."],"formattedPrice":"$169.99"},
      {"title":"ibagbar Canvas Messenger Bag Shoulder Bag Laptop Bag Computer Bag Satchel Bag Bookbag School Bag Working Bag for Men and Women (Dark Gray Large)","brand":"Ibagbar","detailPageUrl":"https://www.amazon.com/ibagbar-Messenger-Shoulder-Computer-Satchel/dp/B01M8FAW0T?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01M8FAW0T", "key": "B01M8FAW0T","image":"https://images-na.ssl-images-amazon.com/images/I/51JKcfYuZ%2BL.jpg","details":["About the strap rip: We have used better leather and better sewing method. ...","Structure: A total of 9 pockets. 1 main zipper Pocket, 1 front zipper pocke...","Approx Dimensions: ( Small: 13\" L x 11\" H x 3.5\"W ) , ( Large: 14\" L x 12\" ...","Warranty: All of our bags have 1-YEAR WARRANTY. Any problems with your bag,..."],"formattedPrice":"$23.99"},
      {"title":"Venture Pal Ultralight Lightweight Packable Foldable Travel Camping Hiking Outdoor Sports Backpack Daypack (Black)","brand":"Venture Pal","detailPageUrl":"https://www.amazon.com/Venture-Pal-Ultralight-Lightweight-Packable/dp/B01BY6UDEQ?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01BY6UDEQ", "key": "B01BY6UDEQ","image":"https://images-na.ssl-images-amazon.com/images/I/41jfkOlkl9L.jpg","details":["DURABLE. This Venture Pal Backpack is made with high quality tear and water...","COMFORTABLE. Breathable mesh shoulder straps with plentiful sponge padding ...","MULTI COMPARTMENTS and KEEP THINGS ORGANIZED. This backpack features one ma...","LIGHTWEIGHT(0.7LB) and ROOMY(35Liters).A true space saver. Fold the backpac..."],"formattedPrice":"$68.99"},
      {"title":"iPhone 7 Case, Allovit [Ultra-Thin]& [Anti-stain] Premium Matte TPU Material Full Protection Hard Cover for iPhone 7 4.7'' (Matte Black)","brand":"Allovit","detailPageUrl":"https://www.amazon.com/Allovit-Ultra-Thin-Anti-stain-Material-Protection/dp/B01N2XMIAV?SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01N2XMIAV","image":"https://images-na.ssl-images-amazon.com/images/I/41Fo4r06tsL.jpg","details":["※ Specialist design for iPhone 7 ensures cell phone to get full protection.","※Smooth touch: Premium TPU material provides smooth skin texture and also r...","※Ultra-Thin Experience : Only 0.8mm thickness is one of the lightness desig...","※Premium Protect: 0.3mm thicken hole design can protect the camera on the p..."],"formattedPrice":"$9.99","key":"B01N2XMIAV"},
      {"title":"Nike Men's Free 5.0+ Running Shoe (11)","brand":"Nike","detailPageUrl":"https://www.amazon.com/Nike-Mens-Free-Running-Shoe/dp/B0098G8FKY?psc=1&Subs…vestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B0098G8FKY","image":"https://images-na.ssl-images-amazon.com/images/I/416-yuIyKOL.jpg","details":["Textured mesh full inner sleeve for a dynamic, sock-like fit and easy on and off,Asymmetrical lacing system for reduced pressure on the top ridge of the foot,Diagonal cuts through the arch to encourage natural motion and help increase foot strength"],"formattedPrice":"$100.00","key":"B0098G8FKY"},
        {"title":"Razer DeathAdder Chroma - Multi-Color Ergonomic Gaming Mouse - 10,000 DPI Sensor - Comfortable Grip - World's Most Popular Gaming Mouse","brand":"Razer","detailPageUrl":"https://www.amazon.com/Razer-DeathAdder-Chroma-Multi-Color-Comfortable/dp/B00MYTSDU4?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B00MYTSDU4","image":"https://images-na.ssl-images-amazon.com/images/I/41SvcggT3xL.jpg","details":["Perfectly designed to fit snugly under your palm, the ergonomic shape of the Razer DeathAdder Chroma gives gamers the most comfortable gaming experience ever, especially during the most testing of battles.,The Razer DeathAdder Chroma is equipped with a 10,000dpi optical sensor. It is capable of mouse movement speeds of up to 200 inches per second and 50g acceleration.,Whether your playing at fast or low speeds, the Deathadder Chroma will always respond onscreen with exacting accuracy and the organic fluidity only possible with an optical sensor.,The Razer DeathAdder Chroma's sensor is also capable of tracking Z-axis to as low as 1mm on most surfaces including glass table tops. This is perfect for low-sense gamers who want to set tracking to cut-off as soon as they lift their mice.,Chroma lighting with 16.8 million customizable color options Whether you're in the mood for electric blue, pastel pink, or signature Razer green, you can now illuminate your Razer DeathAdder Chroma's scroll wheel and Razer logo just the way you want."],"formattedPrice":"$49.99","key":"B00MYTSDU4"},
      {"title":"LOGITECH G430 DTS Headphone: X and Dolby 7.1 Surround Sound Gaming Headset (981-000536)","brand":"Logitech","detailPageUrl":"https://www.amazon.com/LOGITECH-G430-DTS-Headphone-981-000536/dp/B00CQ35C1Q?SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B00CQ35C1Q","image":"https://images-na.ssl-images-amazon.com/images/I/41uTJ%2BpyZ-L.jpg","details":["DTS Headphone: X and Dolby 7.1 surround sound: Experience an immersive 360-degree sound field that lets you hear what you can't see,Built for comfort: Lightweight design and soft sport cloth ear cups with 90-degree swivel for maximum comfort and a personalized fit,Folding, noise-cancelling boom mic: Reduces background noise for clear voice pick up and rotates up and out of the way,On-cable sound controls: Volume dial and mute switch are close at hand for quick audio adjustments,Compatibility: Works with PS4 and Windows 10, Windows 8, Windows 7 or Windows Vista computers"],"formattedPrice":"$39.99","key":"B00CQ35C1Q"},
      {"title":"Sunorm 3.5mm In-Ear Sports Earphone Translucent Ear-buds with Detachable Long Cable Compatible with Apple iPhone and Android Smart phones and Tablets (Translucent Red)","brand":"Sunorm","detailPageUrl":"https://www.amazon.com/Sunorm-Earphone-Translucent-Detachable-Compatible/dp/B01ISZEEFA?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01ISZEEFA","image":"https://images-na.ssl-images-amazon.com/images/I/41CotydaKwL.jpg","details":["Translucent housings design, Here are three colors : red, blue and dark brown for your choice,Lightweight soft silicone earbuds. Five extra earpieces are offered. Multi-choice and comfortable fit,Long and tangle free cable is detachable.The cable of the ear-phone is up to 47.2 inch. Listen to music with your phone far away become possible,Easy operation, durable with nice sound for music enjoyment. Whether the young or the elder can use it freely,Packing list: 1 x earphone; 5 extra pairs of earpiece; 1 x pouch"],"formattedPrice":"$45.00","key":"B01ISZEEFA"},
      {"title":"Bose QuietComfort 25 Acoustic Noise Cancelling Headphones for Apple Devices, Black","brand":"Bose","detailPageUrl":"https://www.amazon.com/Bose-QuietComfort-Acoustic-Cancelling-Headphones/dp/B00M1NEUKK?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B00M1NEUKK","image":"https://images-na.ssl-images-amazon.com/images/I/51xNccRxpsL.jpg","details":["Significant Noise Reduction For Travel,Deep, Powerful Sound For The Music You Love,Inline Mic/remote For Music And Calls,Designed specifically for use with select iPod, iPhone and iPad models,These headphones are compatible with most Android, Windows and BlackBerry smartphones"],"formattedPrice":"$299.00","key":"B00M1NEUKK"},
      {"title":"BLACK+DECKER T2569B 2-Slice Toaster, Bagel Toaster, Black","brand":"BLACK+DECKER","detailPageUrl":"https://www.amazon.com/BLACK-DECKER-T2569B-2-Slice-Toaster/dp/B002CVTT4S?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B002CVTT4S","image":"https://images-na.ssl-images-amazon.com/images/I/41t-qi6unIL.jpg","details":["850-watt 2-slice toaster with self-centering, extra-wide slots,Browning-control knob for selecting the shade from light to dark,Push-button controls; frozen, bagel, and cancel functions with indicator lights,Electronic toast control; cord storage; slide-out crumb tray ensures quick cleanup,Product Built to North American Electrical Standards"],"formattedPrice":"$26.99","key":"B002CVTT4S"},
      {
        "title": "Earphones,Magnet Attraction Sport In-Ear Earbuds Heaphones Headset Stereo Bass with Mic (Green)",
        "brand": "ANHEY",
        "detailPageUrl": "https://www.amazon.com/Earphones-Attraction-Earbuds-Heaphones-Headset/dp/B01LXMBVIF?psc=1&SubscriptionId=AKIAILTVDPVJHFO5NCWA&tag=fivestario-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=B01LXMBVIF",
        "image": "https://images-na.ssl-images-amazon.com/images/I/41zemF3n5EL.jpg",
        "details": [
          "Wired Noise Cancelling Headset Earbuds, - Comfortable in-ear design with soft silicone sweat-proof eartips reduce outside noise, so you can enjoy music on the go. Come with 3 different ear tips in L/M/S size for your choice.,Super Distortion-free Bass Effect In-Ear Sports - Lightweight and water-proof make it perfect to keep moving during daily workouts, also you can use this earphone at home when gaming, listening music.,Multifunction Control Earphones with In-line Mic - The Built-in hands-free microphone allows you to easily enjoy uninterrupted music or talk on your phone everywhere. The multifunction button will control volume +/-, answer/end calls.,Stereo Headset Earbuds 3.5mm Jack - Ideal for Apple devices; Android smartphones; windows phones; MP3/MP4 player, iPad, iPod; most Samsung Galaxy and Note series, Nexus, HTC, laptops, tablets and other devices with 3.5 mm interface"
        ],
        "formattedPrice": "$12.99",
        "key": "B01LXMBVIF"
      }
    ]
  }
]
